### ISSUE TITLE
android::Thread::_threadLoop : After scrolling the screen up and down all the way, the app crashes on Android

### ISSUE THREAD

**Issue by SlavaC7** [LKHcoding/react-native-blur-effect#1]
found the error through sentry, I installed the "react-native-blur-effect" library: "^1.1.3", and useing like this:
`
export const Blur = ({ children, isList, width }: TBlurCategoryProps) => (
  <>
    {isList && <>{children}</>}
    {!isList && (
      <FlexWrapper style={styles.main} width={'auto'} height={'44px'}>
        <BlurContainer
          width={width}
          blurRadius={4}
          backgroundColor="rgba(37, 37, 37, 0.6)"
        />
        {children}
      </FlexWrapper>
    )}
  </>
)

export const BlurContainer = styled(BlurView)<{ width: number }>`
  height: 44px;
  width: 30px;
  position: absolute;
  top: 0;
  align-self: center;
`
`

to all this bluer behavior is weird, like in the video:

Uploading video_2024-05-07_14-31-18.mp4…

`
    "react-native-blur-effect": "^1.1.3",
    "react-native": "0.71.4",
    "react": "18.2.0",
`

**Comment by LKHcoding** [comment]
@SlavaC7 
Which version of react-native-webview are you using?  
Please ensure it's above ^13.6.2
