### ISSUE TITLE
Blurring if the components are  the same level

### ISSUE THREAD

**Issue by Bayramito** [LKHcoding/react-native-blur-effect#2]
### Link to the code that reproduces this issue

*

### To Reproduce

Simply if you use blur in a absolute positioned `Header` component let's say, and if you put this above a List component it's not blurring the list elements once they below the Header. It works only if BlurView and List compnents are at the same level of children tree

### Current vs. Expected behavior

*

### Provide environment information

```bash
*
```

### Which OS(s) are affected? (Select all that apply)

AOS

**Comment by LKHcoding** [comment]
@Bayramito 
Yes, it's as you said.
I don't know what the problem is?

Please write an example of the code that reproduced the problem
and an example of the improvement.

**Comment by Bayramito** [comment]
Found a solution thank you

**Comment by Bayramito** [comment]
Btw, i found another bug... when you apply `overflow:"hidden"` to parent element of  the blur, it's not working

**Comment by LKHcoding** [comment]
> Btw, i found another bug... when you apply `overflow:"hidden"` to parent element of the blur, it's not working

@Bayramito 
Not related to the current issue
You'll need to open a separate issue with the examples
