### ISSUE TITLE
Works properly on iOS simulator on Andriod either there is an overlay of white screen or completely blank white screen

### ISSUE THREAD

**Issue by waleedauthornate** [LKHcoding/react-native-blur-effect#3]
### Link to the code that reproduces this issue

https://github.com/LKHcoding/react-native-blur-effect/issues/new?assignees=&labels=bug&projects=&template=1.bug_report.yml

### To Reproduce

To reproduce the error just navigate to the screen that has BlurView used in it

### Current vs. Expected behavior

I used <BlurView> in react-native app and am running on both iOS and Andriod
It works perfectly fine on the iOS devices but on the Andriod there is a white overlay or completely white screen.

Have made multiple builds to test on a physical device and the behavior is the same!!! 

### Provide environment information

```bash
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 42.89 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: /private/var/folders/w8/fp6frkq95rdg4d__j9cvrymc0000gn/T/xfs-2458dabf/node
  Yarn:
    version: 3.6.4
    path: /private/var/folders/w8/fp6frkq95rdg4d__j9cvrymc0000gn/T/xfs-2458dabf/yarn
  npm:
    version: 10.7.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.07.01.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Which OS(s) are affected? (Select all that apply)

AOS

**Comment by LKHcoding** [comment]
@waleedauthornate 
Can you provide a screenshot or video of the issue?

**Comment by waleedauthornate** [comment]
//THATS SOMETHING I CAME UP WITH TO COVER FOR BOTH
import {BlurView} from ***@***.***/blur';
import React from 'react';
import {
View,
Text,
Image,
ImageSourcePropType,
TouchableOpacity,
Platform,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import {Divider} from 'react-native-paper';
import styled from 'styled-components';

interface ChallengeCardProps {
navigation?: any;
usrIcn: ImageSourcePropType;
tags: [string, string];
displayImage: ImageSourcePropType;
displayDateTitle: string[];
dueDateDescription: string[];
prize: string;
entry: string;
path?: string;
share?: boolean;
}

export default function ChallengeCard({
navigation,
usrIcn,
tags,
displayImage,
displayDateTitle,
dueDateDescription,
prize,
entry,
path,
share,
}: ChallengeCardProps): React.JSX.Element {
return (
<>
<ChallengeParent
onPress={path ? () => navigation.navigate(path) : () => {}}>
{/* @ts-ignore */}
<Challenge>
<GlassImage source={displayImage} />
{Platform.OS === 'ios' && (
<BlurView
blurAmount={20}
blurType="dark"
reducedTransparencyFallbackColor="white">
{share ? (
<ShareTag>
<Tag>
<Image source={require('../assets/icons/share.png')} />
<NameText>Share</NameText>
</Tag>
</ShareTag>
) : (
<ChallengeTags>
<NameTag>
<Image source={usrIcn} />
<NameText>{tags[0]}</NameText>
</NameTag>
<NumberTag>
<Image source={usrIcn} />
<NumberText>{tags[1]}</NumberText>
</NumberTag>
</ChallengeTags>
)}
<ChallengeVisual>
{/* @ts-ignore */}
<Overlay />
<MainImage source={displayImage} />
<VisualDetail>
<Day>Day 2: {displayDateTitle[0]}</Day>
<Title>{displayDateTitle[1]}</Title>
</VisualDetail>
</ChallengeVisual>
<ChallengeDetails>
<DetailTop>
<DateMode>{dueDateDescription[0]}</DateMode>
<TotalSkills>{dueDateDescription[1]}</TotalSkills>
</DetailTop>
<StyledDivider />
<DetailBottom>
<Prize>
<PrizeTitle>Prize Pool</PrizeTitle>
<PrizeValue>
<Image source={require('../assets/icons/rocket.png')} />
<PrizePool>{prize}</PrizePool>
</PrizeValue>
</Prize>
<EnrollmentCost>
<EnrollmentTitle>Entry</EnrollmentTitle>
<EnrollmentValue>
<Image
source={require('../assets/icons/dollar-circle.png')}
/>
<Value>{entry}</Value>
</EnrollmentValue>
</EnrollmentCost>
</DetailBottom>
</ChallengeDetails>
</BlurView>
)}
{Platform.OS === 'android' && (
<OuterView>
{share ? (
<ShareTag>
<Tag>
<Image source={require('../assets/icons/share.png')} />
<NameText>Share</NameText>
</Tag>
</ShareTag>
) : (
<ChallengeTags>
<NameTag>
<Image source={usrIcn} />
<NameText>{tags[0]}</NameText>
</NameTag>
<NumberTag>
<Image source={usrIcn} />
<NumberText>{tags[1]}</NumberText>
</NumberTag>
</ChallengeTags>
)}
<ChallengeVisual>
{/* @ts-ignore */}
<Overlay />
<MainImage source={displayImage} />
<VisualDetail>
<Day>Day 2: {displayDateTitle[0]}</Day>
<Title>{displayDateTitle[1]}</Title>
</VisualDetail>
</ChallengeVisual>
<ChallengeDetails>
<DetailTop>
<DateMode>{dueDateDescription[0]}</DateMode>
<TotalSkills>{dueDateDescription[1]}</TotalSkills>
</DetailTop>
<StyledDivider />
<DetailBottom>
<Prize>
<PrizeTitle>Prize Pool</PrizeTitle>
<PrizeValue>
<Image source={require('../assets/icons/rocket.png')} />
<PrizePool>{prize}</PrizePool>
</PrizeValue>
</Prize>
<EnrollmentCost>
<EnrollmentTitle>Entry</EnrollmentTitle>
<EnrollmentValue>
<Image
source={require('../assets/icons/dollar-circle.png')}
/>
<Value>{entry}</Value>
</EnrollmentValue>
</EnrollmentCost>
</DetailBottom>
</ChallengeDetails>
</OuterView>
)}
</Challenge>
</ChallengeParent>
</>
);
}

const ChallengeParent = styled(TouchableOpacity)`
display: flex;
flex-direction: column;
margin: 0px 10px;
`;
const Challenge = styled(View)`
position: relative;
display: flex;
margin: 10px;
overflow: hidden;
border-radius: 25px;
border: 1px solid #ffffff2f;
`;
const OuterView = styled(View)`
background-color: rgba(0, 0, 0, 0.8);
`;
const GlassImage = styled(Image)`
position: absolute;
top: 0px;
left: 0px;
height: 100%;
width: 100%;
`;
const ChallengeVisual = styled(View)`
position: relative;
width: 100%;
border-radius: 25px;
overflow: hidden;
`;
const Overlay = styled(LinearGradient).attrs({
colors: ['rgba(0, 0, 0, 0)', 'rgba(0, 0, 0, 0.4)', '#000000ee'],
start: {x: 0, y: 0.2},
end: {x: 0, y: 0.9},
})`
position: absolute;
top: 0;
left: 0;
z-index: 1;
width: 100%;
height: 250px;
`;
const ChallengeTags = styled(View)`
position: absolute;
top: 10px;
left: 0px;
display: flex;
flex-direction: row;
justify-content: space-between;
padding: 0px 15px;
z-index: 1;
width: 100%;
`;
const NameTag = styled(View)`
display: flex;
flex-direction: row;
align-items: center;
background-color: rgba(0, 0, 0, 0.6);
border-radius: 25px;
padding: 5px 10px;
`;
const NameText = styled(Text)`
color: #fff;
font-weight: 600;
padding-left: 5px;
`;
const NumberTag = styled(View)`
display: flex;
flex-direction: row;
align-items: center;
background-color: rgba(0, 0, 0, 0.6);
border-radius: 25px;
padding: 5px 10px;
`;
const NumberText = styled(Text)`
color: #fff;
font-weight: 600;
padding-left: 5px;
`;
const MainImage = styled(Image)`
width: 100%;
height: 250px;
`;
const VisualDetail = styled(View)`
position: absolute;
bottom: 10px;
left: 20px;
z-index: 3;
`;
const Day = styled(Text)`
color: #fff;
font-size: 12px;
opacity: 0.7;
padding-bottom: 5px;
`;
const Title = styled(Text)`
color: #fff;
font-size: 20px;
font-weight: 500;
`;
const ChallengeDetails = styled(View)`
padding: 20px 15px;
`;
const DetailTop = styled(View)``;
const StyledDivider = styled(Divider)`
margin: 10px 0px;
`;
const DateMode = styled(Text)`
font-size: 12px;
opacity: 0.7;
padding-bottom: 5px;
color: #fff;
`;
const TotalSkills = styled(Text)`
font-size: 18px;
color: #fff;
font-weight: 500;
`;
const DetailBottom = styled(View)`
display: flex;
flex-direction: row;
width: 100%;
`;
const Prize = styled(View)`
display: flex;
flex-direction: column;
width: 50%;
`;
const PrizeTitle = styled(Text)`
color: #fff;
font-size: 12px;
opacity: 0.7;
padding-bottom: 5px;
`;
const PrizeValue = styled(View)`
display: flex;
flex-direction: row;
align-items: center;
justify-content: flex-start;
`;
const PrizePool = styled(Text)`
color: #fff;
padding-left: 5px;
`;
const EnrollmentCost = styled(View)`
flex-direction: column;
width: 50%;
/* border: 1px solid green; */
`;
const EnrollmentTitle = styled(Text)`
font-size: 12px;
opacity: 0.7;
padding-bottom: 5px;
color: #fff;
`;
const EnrollmentValue = styled(View)`
display: flex;
flex-direction: row;
justify-content: flex-start;
align-items: center;
`;
const Value = styled(Text)`
font-size: 18px;
color: #fff;
font-weight: 500;
padding-left: 5px;
`;
const ShareTag = styled(View)`
position: absolute;
top: 10px;
left: 0px;
display: flex;
flex-direction: row;
justify-content: flex-end;
padding: 0px 15px;
z-index: 1;
width: 100%;
`;
const Tag = styled(View)`
display: flex;
flex-direction: row;
align-items: center;
background-color: rgba(0, 0, 0, 0.6);
border-radius: 25px;
padding: 5px 10px;
`;

**Comment by waleedauthornate** [comment]
https://github.com/user-attachments/assets/ee2ac89d-40d4-4d9c-b9af-a5457fa39d5a

**Comment by LKHcoding** [comment]
@waleedauthornate 

I made an example for android.
There is no problem.
Your styling approach seems like it could be problematic.
You can check the example code in the 'README.md'.


https://github.com/user-attachments/assets/b2b783ad-b5ce-423c-ab6b-f1a8b807a1d9

**Comment by waleedauthornate** [comment]
<StyledImage 
  resizeMode="cover" 
  source={imgSrc} 
  blurRadius={1} 
/>

Found it!!
Thanks anyways

**Comment by waleedauthornate** [comment]
StyledImage 
  resizeMode="cover" 
  source={imgSrc} 
  blurRadius={1}

**Comment by kelvinOfoli** [comment]
let's take a moment to acknowledge @LKHcoding you've solved a long last problem in react native with your discovery.. 🙌

**Comment by waleedauthornate** [comment]
```<StyledImage 
  resizeMode="cover" 
  source={imgSrc} 
  blurRadius={1} 
/> 
Found it thanks!

**Comment by LKHcoding** [comment]
@kelvinOfoli 
thanks :)
